package caldavgw

import (
	"fmt"
	"net/http"
	"strings"
	"time"
)

func (h *Handler) serveTimezone(w http.ResponseWriter, r *http.Request) {
	tzid := strings.TrimPrefix(r.URL.Path, "/caldav/timezones/")
	tzid = strings.TrimSuffix(tzid, "/")
	if tzid == "" {
		http.Error(w, "timezone ID is required", http.StatusBadRequest)
		return
	}
	loc, err := time.LoadLocation(tzid)
	if err != nil {
		http.Error(w, "unsupported timezone", http.StatusNotFound)
		return
	}
	vtimezone, err := buildVTIMEZONE(tzid, loc)
	if err != nil {
		http.Error(w, "failed to build timezone data", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/calendar; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=86400")
	w.WriteHeader(http.StatusOK)
	if r.Method == MethodHead {
		return
	}
	w.Write(vtimezone)
}

func buildVTIMEZONE(tzid string, loc *time.Location) ([]byte, error) {
	_, offset := time.Now().In(loc).Zone()
	utcOffset := formatUTCOffset(offset)
	now := time.Now().UTC().Format(time.RFC3339)
	var b strings.Builder
	b.WriteString("BEGIN:VCALENDAR\r\n")
	b.WriteString("VERSION:2.0\r\n")
	b.WriteString("PRODID:-//gogomail//CalDAV Timezone Service//EN\r\n")
	b.WriteString("CALSCALE:GREGORIAN\r\n")
	b.WriteString("METHOD:PUBLISH\r\n")
	b.WriteString("BEGIN:VTIMEZONE\r\n")
	b.WriteString("TZID:")
	b.WriteString(tzid)
	b.WriteString("\r\n")
	b.WriteString("BEGIN:STANDARD\r\n")
	b.WriteString("TZOFFSETFROM:")
	b.WriteString(utcOffset)
	b.WriteString("\r\n")
	b.WriteString("TZOFFSETTO:")
	b.WriteString(utcOffset)
	b.WriteString("\r\n")
	b.WriteString("TZNAME:")
	b.WriteString(tzid)
	b.WriteString("\r\n")
	b.WriteString("DTSTART:19700101T000000Z\r\n")
	b.WriteString("END:STANDARD\r\n")
	b.WriteString("X-LIC-LOCATION:")
	b.WriteString(tzid)
	b.WriteString("\r\n")
	b.WriteString("END:VTIMEZONE\r\n")
	b.WriteString("X-WR-CALDESC:Generated by gogomail CalDAV Timezone Service\r\n")
	b.WriteString("X-PUBLISHED-LL:")
	b.WriteString(now)
	b.WriteString("\r\n")
	b.WriteString("END:VCALENDAR\r\n")
	return []byte(b.String()), nil
}

func formatUTCOffset(seconds int) string {
	abs := seconds
	if abs < 0 {
		abs = -abs
	}
	hours := abs / 3600
	minutes := (abs % 3600) / 60
	sign := "+"
	if seconds < 0 {
		sign = "-"
	}
	return fmt.Sprintf("%s%02d%02d", sign, hours, minutes)
}
